# 服务器端口
server:
  port: 8080
  # Mybatis配置
  # mybatis:
  # mapper-locations: classpath:mappers/*.xml
  # type-aliases-package: com.willpower.travel.pojo
# mybatis plus 的配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 是否开启自动驼峰命名规则（camel case）映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印中间的sql语句
  global-config:
    banner: false   # 控制台是否 print mybatis-plus 的 LOGO
  type-aliases-package: com.willpower.travel.pojo
spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://1.116.208.186:3306/oldtravel?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: aj
    password: 990716
  # 配置thymeleaf模板引擎
  thymeleaf:
    cache: false  # false：不要缓存 修改了模板，自动生效 ctrl+f9:编译生效
    check-template-location: true # 检查模板引擎的位置
    mode: HTML5   # 模板为H5
    prefix: classpath:templates/ # 模板的位置
    suffix: .html # 模板的后缀
    servlet:
      content-type: 'text/html' # 文件的类型
    encoding: UTF-8   # 编码格式
  mvc:
    view:
      prefix: classpath:templates/
      suffix: .html